//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRAKTIKA1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUSHI_STORE
    {
        public int ID_SUSHI_STORE { get; set; }
        public string NAME_POVARA { get; set; }
        public int COLVO_SUSHI { get; set; }
        public int SUSHI_ID { get; set; }
        public int INGREDIENT_ID { get; set; }
        public string GRADE_SUSHI { get; set; }
    
        public virtual INGREDIENTS INGREDIENTS { get; set; }
        public virtual SUSHI SUSHI {private get; set; }
    }
}
